import type {
  BlogPost,
  Certification,
  Experience,
  GalleryItem,
  Membership,
  Profile,
  Project,
  Recommendation,
  SocialLink,
  Technology,
} from '@/types';

export interface CmsContent {
  seoSettings: {
    siteTitle: string;
    siteDescription: string;
    canonicalUrl: string;
    ogImageUrl: string;
    twitterImageUrl: string;
    noindex: boolean;
    nofollow: boolean;
  };
  profile: Profile;
  siteSettings: {
    footer: {
      leadText: string;
      linkLabel: string;
      copyright: string;
      backToPortfolioLabel: string;
      contactPrompt: string;
    };
    blog: {
      title: string;
      description: string;
      backLabel: string;
    };
  };
  hero: {
    roles: string[];
    availabilityLabel: string;
    profileImageUrl: string;
  };
  about: {
    paragraphs: string[];
  };
  experiences: Experience[];
  projects: Project[];
  certifications: Certification[];
  galleryImages: GalleryItem[];
  memberships: Membership[];
  recommendations: Recommendation[];
  socialLinks: SocialLink[];
  technologies: Technology[];
  techCategories: Record<string, Technology[]>;
  blogPosts: BlogPost[];
}

export const fallbackBlogPosts: BlogPost[] = [
  {
    id: '1',
    slug: 'hello-world',
    title: 'Hello World',
    excerpt: 'Intro',
    content: '# Hello World\n\nThis is the first post in the portfolio blog.',
    date: '2026-01-10',
    readTime: '5 min',
    tags: ['AI', 'Web'],
    coverImage: '/images/blog/hello-world.jpg',
    featured: true,
    metaTitle: 'Hello World',
    metaDescription: 'Intro post for the portfolio blog.',
  },
  {
    id: '2',
    slug: 'deep-dive',
    title: 'Deep Dive',
    excerpt: 'Deep dive',
    content: '## Deep Dive\n\nA deeper look at the work behind the portfolio.',
    date: '2026-02-20',
    readTime: '7 min',
    tags: ['Cloud', 'Next.js'],
    coverImage: '/images/blog/deep-dive.jpg',
    featured: false,
    metaTitle: 'Deep Dive',
    metaDescription: 'A deeper look at the work behind the portfolio.',
  },
];

export function buildTechCategories(technologies: Technology[]): Record<string, Technology[]> {
  return technologies.reduce<Record<string, Technology[]>>((acc, technology) => {
    if (!acc[technology.category]) {
      acc[technology.category] = [];
    }

    acc[technology.category].push(technology);
    return acc;
  }, {});
}

const emptyProfile: Profile = {
  name: '',
  title: '',
  email: '',
  phone: '',
  location: '',
  github: '',
  linkedin: '',
  summary: '',
  highlights: {
    yearsExperience: 0,
    projectsCompleted: 0,
    primaryTechnologies: [],
  },
  education: [],
};

export const fallbackCmsContent: CmsContent = {
  seoSettings: {
    siteTitle: 'Jhon Keneth Namias | Portfolio king of stuff',
    siteDescription: 'Personal portfolio of Jhon Keneth Namias.',
    canonicalUrl: 'https://namias.tech',
    ogImageUrl: '/og-image.svg',
    twitterImageUrl: '/og-image.svg',
    noindex: false,
    nofollow: false,
  },
  profile: emptyProfile,
  siteSettings: {
    footer: {
      leadText: '',
      linkLabel: '',
      copyright: '',
      backToPortfolioLabel: 'Back to Portfolio',
      contactPrompt: 'Send a message',
    },
    blog: {
      title: 'Blog',
      description: 'Thoughts on AI, software engineering, cloud development, and more.',
      backLabel: 'Back to Portfolio',
    },
  },
  hero: {
    roles: [],
    availabilityLabel: '',
    profileImageUrl: '',
  },
  about: {
    paragraphs: [],
  },
  experiences: [],
  projects: [
    {
      title: 'Namias Portfolio',
      image: '',
      description: 'Production portfolio with AI chat, Sanity CMS, and 278 tests',
      tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity', 'Web Application'],
      year: 2025,
      category: 'Web Application',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Portfolio',
      liveURL: 'https://namias.tech',
      processURL: null,
      detailURL: null,
      status: 'in-progress',
      tier: 'featured',
      showcaseDetail: false,
      shortDescription: 'Production portfolio with AI chat, Sanity CMS, and 278 tests',
      highlights: ['278 tests with react-doctor 100/100 score', '19 CI/CD workflows with GitHub Actions', 'AI chat integration', 'PentestAgent security scanning'],
      githubRepo: 'Portfolio',
      slug: 'namias-portfolio',
    },
    {
      title: 'CaseMaster',
      image: '',
      description: 'A comprehensive case management system with Office login and email integration',
      tags: ['Desktop Application', 'Microsoft Office', 'Email Integration', 'Case Management'],
      year: 2024,
      category: 'Desktop Application',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/CaseMaster',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'A comprehensive case management system with Office login and email integration',
      highlights: ['Microsoft Office integration', 'Email management system', 'Notion-style case tracker', 'Audit logs and archive system'],
      githubRepo: 'CaseMaster',
      slug: 'casemaster',
    },
    {
      title: 'Gigachad Accounting System',
      image: '',
      description: 'Full-featured accounting system with financial tracking and reporting',
      tags: ['Desktop Application', 'Financial Tracking', 'Reporting', 'Multi-user'],
      year: 2024,
      category: 'Desktop Application',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Gigachad-Accounting-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Full-featured accounting system with financial tracking and reporting',
      highlights: ['Financial transaction tracking', 'Invoice management', 'Reporting dashboard', 'Multi-user support'],
      githubRepo: 'Gigachad-Accounting-System',
      slug: 'gigachad-accounting-system',
    },
    {
      title: 'Student Attendance System',
      image: '',
      description: 'Barcode-based attendance tracking with mobile app and admin dashboard',
      tags: ['Education Tech', 'Barcode', 'Mobile App', 'Admin Dashboard'],
      year: 2024,
      category: 'Education Tech',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Student-Attendance-Management-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Barcode-based attendance tracking with mobile app and admin dashboard',
      highlights: ['Barcode-based attendance tracking', 'Mobile app for teachers', 'Admin dashboard with analytics', 'Role-based access control'],
      githubRepo: 'Student-Attendance-Management-System',
      slug: 'student-attendance-system',
    },
    {
      title: 'Billing Management System',
      image: '',
      description: 'Shop management with product CRUD, billing logs, and Excel export',
      tags: ['Desktop Application', 'JavaFX', 'MySQL', 'Excel Export'],
      year: 2024,
      category: 'Desktop Application',
      role: 'Backend Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Billing-Management-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Shop management with product CRUD, billing logs, and Excel export',
      highlights: ['JavaFX 21 modern UI', 'MySQL database integration', 'Excel export functionality', 'Multi-contributor collaboration'],
      githubRepo: 'Billing-Management-System',
      slug: 'billing-management-system',
    },
    {
      title: 'Biometric IoT Attendance',
      image: '',
      description: 'Biometric attendance using IoT fingerprint scanner hardware integration',
      tags: ['IoT', 'Fingerprint Scanner', 'Embedded Systems', 'Hardware Integration'],
      year: 2024,
      category: 'IoT',
      role: 'IoT Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Biometric-Attendance-System-Using-IOT',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Biometric attendance using IoT fingerprint scanner hardware integration',
      highlights: ['Fingerprint scanner integration', 'IoT hardware communication', 'Real-time attendance logging', 'Embedded systems programming'],
      githubRepo: 'Biometric-Attendance-System-Using-IOT',
      slug: 'biometric-iot-attendance',
    },
    {
      title: 'Whisper AI Real-Time',
      image: '',
      description: 'Real-time speech-to-text powered by OpenAI Whisper with GPU acceleration',
      tags: ['AI/ML', 'OpenAI Whisper', 'Speech-to-Text', 'GPU Acceleration'],
      year: 2024,
      category: 'AI/ML',
      role: 'AI/ML Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Whisper_AI_Real_Time',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Real-time speech-to-text powered by OpenAI Whisper with GPU acceleration',
      highlights: ['Real-time speech-to-text transcription', 'Multiple model sizes for different needs', 'GPU acceleration support', 'State-of-the-art AI accuracy'],
      githubRepo: 'Whisper_AI_Real_Time',
      slug: 'whisper-ai-real-time',
    },
    {
      title: 'Whisper AI Subtitles',
      image: '',
      description: 'Generate subtitles and transcriptions from audio/video with Whisper AI',
      tags: ['AI/ML', 'OpenAI Whisper', 'Subtitle Generation', 'Audio Processing'],
      year: 2024,
      category: 'AI/ML',
      role: 'AI/ML Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Whisper-AI-Generate-Subtitles-Transcriptions',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Generate subtitles and transcriptions from audio/video with Whisper AI',
      highlights: ['Audio/video subtitle generation', 'Multiple output formats', 'Batch processing support', 'High accuracy transcription'],
      githubRepo: 'Whisper-AI-Generate-Subtitles-Transcriptions',
      slug: 'whisper-ai-subtitles',
    },
    {
      title: 'Aura AI Discord Bot',
      image: '',
      description: 'AI-powered Discord bot with smart moderation and community features',
      tags: ['Bot', 'Discord.js', 'AI Moderation', 'Community Tools'],
      year: 2025,
      category: 'Bot',
      role: 'Bot Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Aura-AI-Discord-Bot',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: false,
      shortDescription: 'AI-powered Discord bot with smart moderation and community features',
      highlights: ['AI-powered moderation', 'Community engagement features', 'Discord.js integration', 'Automated responses'],
      githubRepo: 'Aura-AI-Discord-Bot',
      slug: 'aura-ai-discord-bot',
    },
    {
      title: 'Pre-Enrollment System',
      image: '',
      description: 'Student pre-enrollment management for Young Achievers School of Caloocan',
      tags: ['Education Tech', 'Student Management', 'Web Application', 'Database'],
      year: 2024,
      category: 'Education Tech',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Pre-enrollment-Management-System',
      liveURL: 'https://pp-namias.github.io/Pre-enrollment-Management-System',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Student pre-enrollment management for Young Achievers School of Caloocan',
      highlights: ['Student data management', 'Enrollment workflow automation', 'Database design and optimization', 'Web application for school admin'],
      githubRepo: 'Pre-enrollment-Management-System',
      slug: 'pre-enrollment-system',
    },
    {
      title: 'Java Rice',
      image: '',
      description: 'An interactive food ordering system built with Java',
      tags: ['Desktop Application', 'Java', 'Food Ordering', 'Java Swing'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Java-Rice',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: true,
      shortDescription: 'An interactive food ordering system built with Java',
      highlights: ['Interactive food ordering UI', 'Order management system', 'Java Swing interface', 'Database integration'],
      githubRepo: 'Java-Rice',
      slug: 'java-rice',
    },
    {
      title: 'ATM System',
      image: '',
      description: 'Automated teller machine application with command line interface',
      tags: ['Desktop Application', 'Python', 'CLI', 'Banking'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/ATM-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Automated teller machine application with command line interface',
      highlights: ['CLI-based interface', 'Transaction processing', 'Account management', 'Python implementation'],
      githubRepo: 'ATM-System',
      slug: 'atm-system',
    },
    {
      title: 'Car Dealership Manager',
      image: '',
      description: 'Car dealership management system built entirely in C++',
      tags: ['Desktop Application', 'C++', 'File I/O', 'Vehicle Management'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Car-Dealership-Management-Program',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Car dealership management system built entirely in C++',
      highlights: ['Vehicle inventory management', 'Sales tracking', 'C++ implementation', 'File I/O operations'],
      githubRepo: 'Car-Dealership-Management-Program',
      slug: 'car-dealership-manager',
    },
    {
      title: 'UCC Student Portal',
      image: '',
      description: 'Front-end design for University of Caloocan City student web application',
      tags: ['Web Application', 'HTML', 'CSS', 'Responsive Design'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/UCC-Student-Portal',
      liveURL: 'https://pp-namias.github.io/UCC-Student-Portal',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Front-end design for University of Caloocan City student web application',
      highlights: ['Responsive student portal UI', 'Modern HTML/CSS design', 'User-friendly navigation', 'University branding'],
      githubRepo: 'UCC-Student-Portal',
      slug: 'ucc-student-portal',
    },
    {
      title: 'UCC Access Module',
      image: '',
      description: 'Module access system for the University of Caloocan City',
      tags: ['Web Application', 'PHP', 'Authentication', 'Database'],
      year: 2023,
      category: 'Web Application',
      role: 'Full-Stack Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/UCC-Access-Module',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Module access system for the University of Caloocan City',
      highlights: ['Secure module access', 'User authentication', 'PHP backend', 'Database integration'],
      githubRepo: 'UCC-Access-Module',
      slug: 'ucc-access-module',
    },
    {
      title: 'Point of Sale System',
      image: '',
      description: 'Point of sale system for retail transaction management',
      tags: ['Desktop Application', 'Transaction Processing', 'Inventory', 'Retail'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Point-of-Sale-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Point of sale system for retail transaction management',
      highlights: ['Transaction processing', 'Product catalog', 'Receipt generation', 'Inventory tracking'],
      githubRepo: 'Point-of-Sale-System',
      slug: 'point-of-sale-system',
    },
    {
      title: 'Banking System',
      image: '',
      description: 'Banking system with account management and transaction processing',
      tags: ['Desktop Application', 'Java', 'Banking', 'Transaction Processing'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Banking-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Banking system with account management and transaction processing',
      highlights: ['Account management', 'Transaction processing', 'Balance inquiries', 'Java implementation'],
      githubRepo: 'Banking-System',
      slug: 'banking-system',
    },
    {
      title: 'DSA in Action',
      image: '',
      description: 'Data structures and algorithms implementation showcase',
      tags: ['Academic', 'Java', 'Data Structures', 'Algorithms'],
      year: 2023,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Final-Program-DSA',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Data structures and algorithms implementation showcase',
      highlights: ['Common data structures', 'Algorithm implementations', 'Performance analysis', 'Java programming'],
      githubRepo: 'Final-Program-DSA',
      slug: 'dsa-in-action',
    },
    {
      title: 'HCI Final Project',
      image: '',
      description: 'Human-Computer Interaction course final project with UI/UX focus',
      tags: ['Web Application', 'UI/UX', 'User Research', 'Prototyping'],
      year: 2023,
      category: 'Web Application',
      role: 'UI/UX Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/HCI-Final-Project',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Human-Computer Interaction course final project with UI/UX focus',
      highlights: ['User-centered design', 'Usability testing', 'Interface prototyping', 'HCI principles application'],
      githubRepo: 'HCI-Final-Project',
      slug: 'hci-final-project',
    },
    {
      title: 'GizDuino Program',
      image: '',
      description: 'GizDuino microcontroller programming for IoT and embedded systems',
      tags: ['IoT', 'Embedded Systems', 'C/C++', 'Microcontroller'],
      year: 2023,
      category: 'IoT',
      role: 'IoT Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/GizDuino-Program',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'GizDuino microcontroller programming for IoT and embedded systems',
      highlights: ['Microcontroller programming', 'Hardware interfacing', 'Sensor integration', 'C/C++ implementation'],
      githubRepo: 'GizDuino-Program',
      slug: 'gizduino-program',
    },
    {
      title: 'Philippines Tourism',
      image: '',
      description: 'Tourism case study website showcasing Philippine natural wonders',
      tags: ['Web Application', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Tourism-Case-Study',
      liveURL: 'https://pp-namias.github.io/Tourism-Case-Study',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Tourism case study website showcasing Philippine natural wonders',
      highlights: ['Responsive tourism website', 'Image gallery showcase', 'HTML/CSS/JS implementation', 'Cultural content presentation'],
      githubRepo: 'Tourism-Case-Study',
      slug: 'philippines-tourism',
    },
    {
      title: 'PHP Login System',
      image: '',
      description: 'PHP-based login and authentication system',
      tags: ['Web Application', 'PHP', 'Authentication', 'Session Management'],
      year: 2023,
      category: 'Web Application',
      role: 'Backend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/PHP-Login',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'PHP-based login and authentication system',
      highlights: ['User authentication', 'Session management', 'PHP backend', 'Database integration'],
      githubRepo: 'PHP-Login',
      slug: 'php-login-system',
    },
    {
      title: 'Simple Program Menu',
      image: '',
      description: 'Odd/Even check and looping exercise in Java',
      tags: ['Academic', 'Java', 'Control Flow', 'Looping'],
      year: 2023,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Simple-Program-Menu',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Odd/Even check and looping exercise in Java',
      highlights: ['Control flow implementation', 'Looping constructs', 'Java basics', 'Menu-driven program'],
      githubRepo: 'Simple-Program-Menu',
      slug: 'simple-program-menu',
    },
    {
      title: 'Passed or Failed',
      image: '',
      description: 'Grade checker application for student evaluation',
      tags: ['Academic', 'Java', 'Grade Calculation', 'Conditional Logic'],
      year: 2023,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Passed-or-Failed',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Grade checker application for student evaluation',
      highlights: ['Grade calculation logic', 'Conditional statements', 'Java implementation', 'Student evaluation tool'],
      githubRepo: 'Passed-or-Failed',
      slug: 'passed-or-failed',
    },
    {
      title: 'Full Name Rotation',
      image: '',
      description: 'Web system for rotating full name in various directions',
      tags: ['Web Application', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Full-Name-Rotation',
      liveURL: 'https://pp-namias.github.io/Full-Name-Rotation',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Web system for rotating full name in various directions',
      highlights: ['CSS text rotation effects', 'Interactive web interface', 'HTML/CSS/JS implementation', 'Midterm web systems project'],
      githubRepo: 'Full-Name-Rotation',
      slug: 'full-name-rotation',
    },
    {
      title: 'Galaxy Animation',
      image: '',
      description: 'Mesmerizing galaxy animation with pure HTML, CSS, and JavaScript',
      tags: ['Web Art', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Galaxy-Animation',
      liveURL: 'https://pp-namias.github.io/Galaxy-Animation',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Mesmerizing galaxy animation with pure HTML, CSS, and JavaScript',
      highlights: ['Pure CSS animations', 'No external dependencies', 'Particle system effects', 'Responsive canvas'],
      githubRepo: 'Galaxy-Animation',
      slug: 'galaxy-animation',
    },
    {
      title: 'CSS3 Robot Art',
      image: '',
      description: 'CSS robot web art created with pure HTML and CSS',
      tags: ['Web Art', 'HTML', 'CSS', 'Creative Design'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/CSS3-Robot-Web-Art',
      liveURL: 'https://pp-namias.github.io/CSS3-Robot-Web-Art',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'CSS robot web art created with pure HTML and CSS',
      highlights: ['Pure CSS artwork', 'Creative design', 'No JavaScript used', 'Web Systems activity'],
      githubRepo: 'CSS3-Robot-Web-Art',
      slug: 'css3-robot-art',
    },
    {
      title: 'CSS3 Robot Animation',
      image: '',
      description: 'Animated robot created with pure CSS3 animations',
      tags: ['Web Art', 'HTML', 'CSS3', 'Animation'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/CSS3-Robot-Animation',
      liveURL: 'https://pp-namias.github.io/CSS3-Robot-Animation',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Animated robot created with pure CSS3 animations',
      highlights: ['CSS3 keyframe animations', 'Character animation', 'Pure CSS implementation', 'Web Systems activity'],
      githubRepo: 'CSS3-Robot-Animation',
      slug: 'css3-robot-animation',
    },
    {
      title: 'CSS3 Egg Asteroid',
      image: '',
      description: 'Egg animation resembling an asteroid floating in space',
      tags: ['Web Art', 'HTML', 'CSS', 'Space Theme'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/CSS3-Egg-Asteroid',
      liveURL: 'https://pp-namias.github.io/CSS3-Egg-Asteroid',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Egg animation resembling an asteroid floating in space',
      highlights: ['Creative CSS animation', 'Space theme design', 'Pure HTML/CSS', 'Web Systems activity'],
      githubRepo: 'CSS3-Egg-Asteroid',
      slug: 'css3-egg-asteroid',
    },
    {
      title: 'Short Clip Animation',
      image: '',
      description: 'Interactive website showcasing the 2011 Bugatti Veyron sports car',
      tags: ['Web Art', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Short-Clip-Animation',
      liveURL: 'https://pp-namias.github.io/Short-Clip-Animation',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Interactive website showcasing the 2011 Bugatti Veyron sports car',
      highlights: ['Interactive car showcase', 'CSS animation effects', 'HTML/CSS/JS implementation', 'Web Systems activity'],
      githubRepo: 'Short-Clip-Animation',
      slug: 'short-clip-animation',
    },
    {
      title: 'Optimus Prime Animation',
      image: '',
      description: 'Transformer character animation created with CSS',
      tags: ['Web Art', 'HTML', 'CSS', 'Character Animation'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Optimus-Prime-Animation',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Transformer character animation created with CSS',
      highlights: ['Character CSS animation', 'Creative design', 'Pure CSS implementation', 'Web art project'],
      githubRepo: 'Optimus-Prime-Animation',
      slug: 'optimus-prime-animation',
    },
    {
      title: 'Floppy Bird',
      image: '',
      description: 'Flappy Bird clone game built with web technologies',
      tags: ['Game', 'HTML', 'Canvas', 'JavaScript'],
      year: 2023,
      category: 'Game',
      role: 'Game Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Floppy-Bird',
      liveURL: 'https://pp-namias.github.io/Floppy-Bird',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Flappy Bird clone game built with web technologies',
      highlights: ['Canvas-based game', 'Physics simulation', 'Score tracking', 'HTML/CSS/JS game'],
      githubRepo: 'Floppy-Bird',
      slug: 'floppy-bird',
    },
    {
      title: 'QR Code Generator',
      image: '',
      description: 'QR code generation application',
      tags: ['Utility', 'Java', 'Image Processing', 'QR Code'],
      year: 2023,
      category: 'Utility',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/QR-Code',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'QR code generation application',
      highlights: ['QR code generation', 'Java implementation', 'Image processing', 'Utility application'],
      githubRepo: 'QR-Code',
      slug: 'qr-code-generator',
    },
    {
      title: 'Calendar 2023',
      image: '',
      description: 'Interactive calendar website for Web Systems activity',
      tags: ['Web Application', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Calendar-2023',
      liveURL: 'https://pp-namias.github.io/Calendar-2023',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Interactive calendar website for Web Systems activity',
      highlights: ['Interactive calendar UI', 'Date navigation', 'HTML/CSS/JS', 'Web Systems activity'],
      githubRepo: 'Calendar-2023',
      slug: 'calendar-2023',
    },
    {
      title: 'GitHub Pages Bio',
      image: '',
      description: 'Personal bio data website hosted on GitHub Pages',
      tags: ['Web Application', 'HTML', 'CSS', 'GitHub Pages'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/PP-Namias.github.io',
      liveURL: 'https://pp-namias.github.io',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Personal bio data website hosted on GitHub Pages',
      highlights: ['GitHub Pages deployment', 'Personal branding', 'HTML/CSS/JS', 'Web Systems activity'],
      githubRepo: 'PP-Namias.github.io',
      slug: 'github-pages-bio',
    },
    {
      title: 'Grade 11 Website',
      image: '',
      description: 'Grade 11 ICT project for Computer Programming course',
      tags: ['Web Application', 'HTML', 'CSS', 'JavaScript'],
      year: 2022,
      category: 'Web Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Website-Project',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Grade 11 ICT project for Computer Programming course',
      highlights: ['Grade 11 coursework', 'HTML/CSS/JS', 'Computer Programming', 'ICT project'],
      githubRepo: 'Website-Project',
      slug: 'grade-11-website',
    },
    {
      title: 'CSD Freshman Bot',
      image: '',
      description: 'Discord bot with 20+ commands for the CSD Freshman server',
      tags: ['Bot', 'Discord.js', 'Node.js', 'Community Tools'],
      year: 2023,
      category: 'Bot',
      role: 'Bot Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/CSD-Bot',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Discord bot with 20+ commands for the CSD Freshman server',
      highlights: ['20+ commands', 'Server management features', 'Discord.js framework', 'Community tooling'],
      githubRepo: 'CSD-Bot',
      slug: 'csd-freshman-bot',
    },
    {
      title: 'UCC Programming Competition',
      image: '',
      description: 'Competition solutions for UCC Programming Competition 2023',
      tags: ['Academic', 'Java', 'Competitive Programming', 'Algorithms'],
      year: 2023,
      category: 'Academic',
      role: 'Competitive Programmer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/UCC-Programing-Competition-2023',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Competition solutions for UCC Programming Competition 2023',
      highlights: ['Algorithm problem solving', 'Competitive programming', 'Java implementation', 'Time-optimized solutions'],
      githubRepo: 'UCC-Programing-Competition-2023',
      slug: 'ucc-programming-competition',
    },
    {
      title: 'Java Program Hub',
      image: '',
      description: 'Collection of Java programs and testing exercises',
      tags: ['Academic', 'Java', 'Testing', 'Code Practice'],
      year: 2023,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Java-Program',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Collection of Java programs and testing exercises',
      highlights: ['Java program collection', 'Testing exercises', 'Learning repository', 'Code practice'],
      githubRepo: 'Java-Program',
      slug: 'java-program-hub',
    },
    {
      title: 'Cube Drift',
      image: '',
      description: 'Cube drift game built with web technologies',
      tags: ['Game', 'HTML', 'Canvas', 'JavaScript'],
      year: 2023,
      category: 'Game',
      role: 'Game Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Cube-Drift',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Cube drift game built with web technologies',
      highlights: ['Canvas-based game', 'Physics simulation', 'HTML/CSS/JS', 'Game development'],
      githubRepo: 'Cube-Drift',
      slug: 'cube-drift',
    },
    {
      title: 'Google Login',
      image: '',
      description: 'Google Authentication with Firebase using HTML, CSS, and JavaScript',
      tags: ['Web Application', 'Firebase', 'Google OAuth', 'Authentication'],
      year: 2023,
      category: 'Web Application',
      role: 'Full-Stack Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Login-with-Google',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Google Authentication with Firebase using HTML, CSS, and JavaScript',
      highlights: ['Firebase authentication', 'Google OAuth integration', 'HTML/CSS/JS implementation', 'Secure login flow'],
      githubRepo: 'Login-with-Google',
      slug: 'google-login',
    },
    {
      title: 'Adventure Typer',
      image: '',
      description: 'Typing adventure game for learning touch typing',
      tags: ['Game', 'JavaScript', 'Educational', 'Typing Game'],
      year: 2023,
      category: 'Game',
      role: 'Game Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/AdventureTyper',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Typing adventure game for learning touch typing',
      highlights: ['Typing game mechanics', 'Adventure theme', 'JavaScript implementation', 'Educational game'],
      githubRepo: 'AdventureTyper',
      slug: 'adventure-typer',
    },
    {
      title: 'First Programming Project',
      image: '',
      description: 'Very first project in programming - the beginning of the coding journey',
      tags: ['Academic', 'C++', 'Learning', 'Fundamentals'],
      year: 2022,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/My-first-project-in-programming',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Very first project in programming - the beginning of the coding journey',
      highlights: ['First programming project', 'Learning fundamentals', 'C++ implementation', 'Beginning of coding journey'],
      githubRepo: 'My-first-project-in-programming',
      slug: 'first-programming-project',
    },
  ],
  certifications: [],
  galleryImages: [],
  memberships: [],
  recommendations: [],
  socialLinks: [],
  technologies: [],
  techCategories: {},
  blogPosts: [],
};

fallbackCmsContent.blogPosts = fallbackBlogPosts;
