apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: portfolio
  namespace: namias
  labels:
    app.kubernetes.io/name: portfolio
    app.kubernetes.io/component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: portfolio
