allowBuilds:
  core-js: false
  esbuild: true
  msw: false
  protobufjs: false
  puppeteer: false
  sharp: false
  workerd: set this to true or false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - shadcn
  - "@base-ui/*"
