/**
 * Project Curator
 *
 * Contains the curated list of projects to import from GitHub,
 * organized by tier (featured, standard, archived) with
 * metadata overrides for Sanity documents.
 */

/**
 * Curated project list with metadata overrides
 * Each entry maps a GitHub repo to its Sanity document fields.
 */
export const CURATED_PROJECTS = [
  // ============================================
  // FEATURED TIER (13 projects)
  // ============================================
  {
    githubRepo: 'Klaro',
    title: 'Klaro',
    shortDescription: 'Full-stack health companion app with Expo and Next.js for Filipino patients',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'Web Application',
    role: 'Full-Stack Developer',
    technologies: ['React Native', 'Expo', 'Next.js', 'TypeScript', 'tRPC', 'Drizzle ORM'],
    highlights: [
      'Full-stack monorepo with mobile (Expo) and web (Next.js) apps',
      'AI-powered medical document analysis',
      'Multilingual chatbot supporting Filipino, Bisaya, and Ilocano',
      'Geolocation-based provider network with PhilHealth filtering',
    ],
  },
  {
    githubRepo: 'Portfolio',
    title: 'Namias Portfolio',
    shortDescription: 'Production portfolio with AI chat, Sanity CMS, and 278 tests',
    tier: 'featured',
    showcaseDetail: false,
    liveURL: 'https://namias.tech',
    category: 'Web Application',
    role: 'Full-Stack Developer',
    technologies: ['Next.js', 'TypeScript', 'Sanity CMS', 'Tailwind CSS', 'Vitest'],
    highlights: [
      '278 tests with react-doctor 100/100 score',
      '19 CI/CD workflows with GitHub Actions',
      'AI chat integration with Gemini',
      'PentestAgent security scanning',
    ],
  },
  {
    githubRepo: 'CaseMaster',
    title: 'CaseMaster',
    shortDescription: 'Comprehensive case management system with Office login and email integration',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'Desktop Application',
    role: 'Full-Stack Developer',
    technologies: ['Java', 'JavaFX', 'MySQL', 'Microsoft Office API'],
    highlights: [
      'Microsoft Office integration',
      'Email management system',
      'Notion-style case tracker',
      'Audit logs and archive system',
    ],
  },
  {
    githubRepo: 'Whisper_AI_Real_Time',
    title: 'Whisper AI Real-Time',
    shortDescription: 'Real-time speech-to-text powered by OpenAI Whisper with GPU acceleration',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'AI/ML',
    role: 'AI/ML Developer',
    technologies: ['Python', 'OpenAI Whisper', 'PyTorch', 'CUDA'],
    highlights: [
      'Real-time speech-to-text transcription',
      'Multiple model sizes for different needs',
      'GPU acceleration support',
      'State-of-the-art AI accuracy',
    ],
  },
  {
    githubRepo: 'Whisper-AI-Generate-Subtitles-Transcriptions',
    title: 'Whisper AI Subtitles',
    shortDescription: 'Generate subtitles and transcriptions from audio/video with Whisper AI',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'AI/ML',
    role: 'AI/ML Developer',
    technologies: ['Python', 'OpenAI Whisper', 'FFmpeg'],
    highlights: [
      'Audio/video subtitle generation',
      'Multiple output formats',
      'Batch processing support',
      'High accuracy transcription',
    ],
  },
  {
    githubRepo: 'Student-Attendance-Management-System',
    title: 'Student Attendance System',
    shortDescription: 'Barcode-based attendance tracking with mobile app and admin dashboard',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'Education Tech',
    role: 'Full-Stack Developer',
    technologies: ['Java', 'Android', 'Firebase', 'QR Code'],
    highlights: [
      'Barcode-based attendance tracking',
      'Mobile app for teachers',
      'Admin dashboard with analytics',
      'Role-based access control',
    ],
  },
  {
    githubRepo: 'Pre-enrollment-Management-System',
    title: 'Pre-Enrollment System',
    shortDescription: 'Student pre-enrollment management for Young Achievers School of Caloocan',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: 'https://pp-namias.github.io/Pre-enrollment-Management-System',
    category: 'Education Tech',
    role: 'Full-Stack Developer',
    technologies: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
    highlights: [
      'Student data management',
      'Enrollment workflow automation',
      'Database design and optimization',
      'Web application for school admin',
    ],
  },
  {
    githubRepo: 'Billing-Management-System',
    title: 'Billing Management System',
    shortDescription: 'Shop management with product CRUD, billing logs, and Excel export',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'Desktop Application',
    role: 'Backend Developer',
    technologies: ['Java', 'JavaFX', 'MySQL', 'Apache POI'],
    highlights: [
      'JavaFX 21 modern UI',
      'MySQL database integration',
      'Excel export functionality',
      'Multi-contributor collaboration',
    ],
  },
  {
    githubRepo: 'Car-Dealership-Management-Program',
    title: 'Car Dealership Manager',
    shortDescription: 'Car dealership management system built entirely in C++',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'Desktop Application',
    role: 'Developer',
    technologies: ['C++', 'File I/O'],
    highlights: [
      'Vehicle inventory management',
      'Sales tracking',
      'C++ implementation',
      'File I/O operations',
    ],
  },
  {
    githubRepo: 'Java-Rice',
    title: 'Java Rice',
    shortDescription: 'An interactive food ordering system built with Java',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'Desktop Application',
    role: 'Developer',
    technologies: ['Java', 'Java Swing'],
    highlights: [
      'Interactive food ordering UI',
      'Order management system',
      'Java Swing interface',
      'Database integration',
    ],
  },
  {
    githubRepo: 'Sage-AI',
    title: 'Sage AI',
    shortDescription: 'AI-powered assistant with intelligent conversation capabilities',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'AI/ML',
    role: 'AI/ML Developer',
    technologies: ['Python', 'OpenAI', 'LangChain'],
    highlights: [
      'Intelligent conversation system',
      'AI-powered responses',
      'Context-aware interactions',
      'Natural language processing',
    ],
  },
  {
    githubRepo: 'Biometric-Attendance-System-Using-IOT',
    title: 'Biometric IoT Attendance',
    shortDescription: 'Biometric attendance using IoT fingerprint scanner hardware integration',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'IoT',
    role: 'IoT Developer',
    technologies: ['Arduino', 'C++', 'Fingerprint Scanner', 'IoT'],
    highlights: [
      'Fingerprint scanner integration',
      'IoT hardware communication',
      'Real-time attendance logging',
      'Embedded systems programming',
    ],
  },
  {
    githubRepo: 'EVOLVE-OR-PERISH',
    title: 'EVOLVE OR PERISH',
    shortDescription: 'Evolution simulation game with genetic algorithms and natural selection',
    tier: 'featured',
    showcaseDetail: true,
    liveURL: null,
    category: 'Game',
    role: 'Game Developer',
    technologies: ['Python', 'Pygame', 'Genetic Algorithms'],
    highlights: [
      'Genetic algorithm simulation',
      'Natural selection mechanics',
      'Real-time visualization',
      'AI creature evolution',
    ],
  },

  // ============================================
  // STANDARD TIER (14 projects)
  // ============================================
  {
    githubRepo: 'Gigachad-Accounting-System',
    title: 'Gigachad Accounting',
    shortDescription: 'Full-featured accounting system with financial tracking and reporting',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Desktop Application',
    role: 'Full-Stack Developer',
    technologies: ['Java', 'JavaFX', 'MySQL'],
    highlights: [
      'Financial transaction tracking',
      'Invoice management',
      'Reporting dashboard',
      'Multi-user support',
    ],
  },
  {
    githubRepo: 'Aura-AI-Discord-Bot',
    title: 'Aura AI Discord Bot',
    shortDescription: 'AI-powered Discord bot with smart moderation and community features',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Bot',
    role: 'Bot Developer',
    technologies: ['JavaScript', 'Discord.js', 'Node.js'],
    highlights: [
      'AI-powered moderation',
      'Community engagement features',
      'Discord.js integration',
      'Automated responses',
    ],
  },
  {
    githubRepo: 'ATM-System',
    title: 'ATM System',
    shortDescription: 'Automated teller machine application with command line interface',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Desktop Application',
    role: 'Developer',
    technologies: ['Python'],
    highlights: [
      'CLI-based interface',
      'Transaction processing',
      'Account management',
      'Python implementation',
    ],
  },
  {
    githubRepo: 'UCC-Student-Portal',
    title: 'UCC Student Portal',
    shortDescription: 'Front-end design for University of Caloocan City student web application',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io/UCC-Student-Portal',
    category: 'Web Application',
    role: 'Frontend Developer',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    highlights: [
      'Responsive student portal UI',
      'Modern HTML/CSS design',
      'User-friendly navigation',
      'University branding',
    ],
  },
  {
    githubRepo: 'UCC-Access-Module',
    title: 'UCC Access Module',
    shortDescription: 'Module access system for the University of Caloocan City',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Web Application',
    role: 'Full-Stack Developer',
    technologies: ['PHP', 'MySQL', 'HTML', 'CSS'],
    highlights: [
      'Secure module access',
      'User authentication',
      'PHP backend',
      'Database integration',
    ],
  },
  {
    githubRepo: 'Point-of-Sale-System',
    title: 'Point of Sale System',
    shortDescription: 'Point of sale system for retail transaction management',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Desktop Application',
    role: 'Developer',
    technologies: ['Java', 'JavaFX', 'MySQL'],
    highlights: [
      'Transaction processing',
      'Product catalog',
      'Receipt generation',
      'Inventory tracking',
    ],
  },
  {
    githubRepo: 'Banking-System',
    title: 'Banking System',
    shortDescription: 'Banking system with account management and transaction processing',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Desktop Application',
    role: 'Developer',
    technologies: ['Java'],
    highlights: [
      'Account management',
      'Transaction processing',
      'Balance inquiries',
      'Java implementation',
    ],
  },
  {
    githubRepo: 'Final-Program-DSA',
    title: 'DSA in Action',
    shortDescription: 'Data structures and algorithms implementation showcase',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Academic',
    role: 'Developer',
    technologies: ['Java'],
    highlights: [
      'Common data structures',
      'Algorithm implementations',
      'Performance analysis',
      'Java programming',
    ],
  },
  {
    githubRepo: 'HCI-Final-Project',
    title: 'HCI Final Project',
    shortDescription: 'Human-Computer Interaction course final project with UI/UX focus',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Web Application',
    role: 'UI/UX Developer',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    highlights: [
      'User-centered design',
      'Usability testing',
      'Interface prototyping',
      'HCI principles application',
    ],
  },
  {
    githubRepo: 'GizDuino-Program',
    title: 'GizDuino Program',
    shortDescription: 'GizDuino microcontroller programming for IoT and embedded systems',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'IoT',
    role: 'IoT Developer',
    technologies: ['Arduino', 'C++'],
    highlights: [
      'Microcontroller programming',
      'Hardware interfacing',
      'Sensor integration',
      'C/C++ implementation',
    ],
  },
  {
    githubRepo: 'Tourism-Case-Study',
    title: 'Philippines Tourism',
    shortDescription: 'Tourism case study website showcasing Philippine natural wonders',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io/Tourism-Case-Study',
    category: 'Web Application',
    role: 'Frontend Developer',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    highlights: [
      'Responsive tourism website',
      'Image gallery showcase',
      'HTML/CSS/JS implementation',
      'Cultural content presentation',
    ],
  },
  {
    githubRepo: 'PHP-Login',
    title: 'PHP Login System',
    shortDescription: 'PHP-based login and authentication system',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Web Application',
    role: 'Backend Developer',
    technologies: ['PHP', 'MySQL', 'HTML', 'CSS'],
    highlights: [
      'User authentication',
      'Session management',
      'PHP backend',
      'Database integration',
    ],
  },
  {
    githubRepo: 'Login-with-Google',
    title: 'Google Login',
    shortDescription: 'Google Authentication with Firebase using HTML, CSS, and JavaScript',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Web Application',
    role: 'Full-Stack Developer',
    technologies: ['JavaScript', 'Firebase', 'HTML', 'CSS'],
    highlights: [
      'Firebase authentication',
      'Google OAuth integration',
      'HTML/CSS/JS implementation',
      'Secure login flow',
    ],
  },
  {
    githubRepo: 'CSD-Bot',
    title: 'CSD Freshman Bot',
    shortDescription: 'Discord bot with 20+ commands for the CSD Freshman server',
    tier: 'standard',
    showcaseDetail: false,
    liveURL: null,
    category: 'Bot',
    role: 'Bot Developer',
    technologies: ['JavaScript', 'Discord.js', 'Node.js'],
    highlights: [
      '20+ commands',
      'Server management features',
      'Discord.js framework',
      'Community tooling',
    ],
  },

  // ============================================
  // ARCHIVED TIER (11 projects)
  // ============================================
  {
    githubRepo: 'Galaxy-Animation',
    title: 'Galaxy Animation',
    shortDescription: 'Mesmerizing galaxy animation with pure HTML, CSS, and JavaScript',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io/Galaxy-Animation',
    category: 'Web Art',
    role: 'Frontend Developer',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    highlights: [
      'Pure CSS animations',
      'No external dependencies',
      'Particle system effects',
      'Responsive canvas',
    ],
  },
  {
    githubRepo: 'CSS3-Robot-Web-Art',
    title: 'CSS3 Robot Art',
    shortDescription: 'CSS robot web art created with pure HTML and CSS',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io/CSS3-Robot-Web-Art',
    category: 'Web Art',
    role: 'Frontend Developer',
    technologies: ['HTML', 'CSS'],
    highlights: [
      'Pure CSS artwork',
      'Creative design',
      'No JavaScript used',
      'Web Systems activity',
    ],
  },
  {
    githubRepo: 'CSS3-Robot-Animation',
    title: 'CSS3 Robot Animation',
    shortDescription: 'Animated robot created with pure CSS3 animations',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io/CSS3-Robot-Animation',
    category: 'Web Art',
    role: 'Frontend Developer',
    technologies: ['HTML', 'CSS'],
    highlights: [
      'CSS3 keyframe animations',
      'Character animation',
      'Pure CSS implementation',
      'Web Systems activity',
    ],
  },
  {
    githubRepo: 'Short-Clip-Animation',
    title: 'Short Clip Animation',
    shortDescription: 'Interactive website showcasing the 2011 Bugatti Veyron sports car',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io/Short-Clip-Animation',
    category: 'Web Art',
    role: 'Frontend Developer',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    highlights: [
      'Interactive car showcase',
      'CSS animation effects',
      'HTML/CSS/JS implementation',
      'Web Systems activity',
    ],
  },
  {
    githubRepo: 'Floppy-Bird',
    title: 'Floppy Bird',
    shortDescription: 'Flappy Bird clone game built with web technologies',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io/Floppy-Bird',
    category: 'Game',
    role: 'Game Developer',
    technologies: ['HTML', 'CSS', 'JavaScript', 'Canvas'],
    highlights: [
      'Canvas-based game',
      'Physics simulation',
      'Score tracking',
      'HTML/CSS/JS game',
    ],
  },
  {
    githubRepo: 'Cube-Drift',
    title: 'Cube Drift',
    shortDescription: 'Cube drift game built with web technologies',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: null,
    category: 'Game',
    role: 'Game Developer',
    technologies: ['HTML', 'CSS', 'JavaScript', 'Canvas'],
    highlights: [
      'Canvas-based game',
      'Physics simulation',
      'HTML/CSS/JS',
      'Game development',
    ],
  },
  {
    githubRepo: 'Calendar-2023',
    title: 'Calendar 2023',
    shortDescription: 'Interactive calendar website for Web Systems activity',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io/Calendar-2023',
    category: 'Web Application',
    role: 'Frontend Developer',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    highlights: [
      'Interactive calendar UI',
      'Date navigation',
      'HTML/CSS/JS',
      'Web Systems activity',
    ],
  },
  {
    githubRepo: 'PP-Namias.github.io',
    title: 'GitHub Pages Bio',
    shortDescription: 'Personal bio data website hosted on GitHub Pages',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: 'https://pp-namias.github.io',
    category: 'Web Application',
    role: 'Frontend Developer',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    highlights: [
      'GitHub Pages deployment',
      'Personal branding',
      'HTML/CSS/JS',
      'Web Systems activity',
    ],
  },
  {
    githubRepo: 'Website-Project',
    title: 'Grade 11 Website',
    shortDescription: 'Grade 11 ICT project for Computer Programming course',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: null,
    category: 'Web Application',
    role: 'Developer',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    highlights: [
      'Grade 11 coursework',
      'HTML/CSS/JS',
      'Computer Programming',
      'ICT project',
    ],
  },
  {
    githubRepo: 'UCC-Programing-Competition-2023',
    title: 'UCC Programming Competition',
    shortDescription: 'Competition solutions for UCC Programming Competition 2023',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: null,
    category: 'Academic',
    role: 'Competitive Programmer',
    technologies: ['Java'],
    highlights: [
      'Algorithm problem solving',
      'Competitive programming',
      'Java implementation',
      'Time-optimized solutions',
    ],
  },
  {
    githubRepo: 'My-first-project-in-programming',
    title: 'First Programming Project',
    shortDescription: 'Very first project in programming - the beginning of the coding journey',
    tier: 'archived',
    showcaseDetail: false,
    liveURL: null,
    category: 'Academic',
    role: 'Developer',
    technologies: ['C++'],
    highlights: [
      'First programming project',
      'Learning fundamentals',
      'C++ implementation',
      'Beginning of coding journey',
    ],
  },
];

/**
 * Get projects filtered by tier
 * @param {string} tier - 'featured' | 'standard' | 'archived'
 * @returns {Array} Filtered projects
 */
export function getProjectsByTier(tier) {
  return CURATED_PROJECTS.filter(p => p.tier === tier);
}

/**
 * Get only showcase projects (showcaseDetail: true)
 * @returns {Array} Showcase projects
 */
export function getShowcaseProjects() {
  return CURATED_PROJECTS.filter(p => p.showcaseDetail);
}

/**
 * Get project by GitHub repo name
 * @param {string} repoName - GitHub repository name
 * @returns {Object|undefined} Project entry
 */
export function getProjectByRepo(repoName) {
  return CURATED_PROJECTS.find(p => p.githubRepo === repoName);
}

/**
 * Get tier counts
 * @returns {Object} Count by tier
 */
export function getTierCounts() {
  return {
    featured: CURATED_PROJECTS.filter(p => p.tier === 'featured').length,
    standard: CURATED_PROJECTS.filter(p => p.tier === 'standard').length,
    archived: CURATED_PROJECTS.filter(p => p.tier === 'archived').length,
    total: CURATED_PROJECTS.length,
  };
}
