/**
 * Sanity Data Health Report
 *
 * Generates a markdown report of data health across all Sanity documents.
 *
 * Usage:
 *   node scripts/sanity-migrate/health-report.mjs
 *   node scripts/sanity-migrate/health-report.mjs --output docs/sanity-health-report.md
 */

import { sanityQuery } from '../lib/sanity-client.mjs';
import { writeFileSync, renameSync, mkdirSync } from 'fs';
import { randomUUID } from 'crypto';
import { dirname } from 'path';

const PROJECT_ID = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || process.env.SANITY_STUDIO_PROJECT_ID;
const DATASET = process.env.NEXT_PUBLIC_SANITY_DATASET || process.env.SANITY_STUDIO_DATASET || 'production';
const TOKEN = process.env.SANITY_API_READ_TOKEN;

const OUTPUT_INDEX = process.argv.indexOf('--output');
const OUTPUT_PATH = OUTPUT_INDEX !== -1 ? process.argv[OUTPUT_INDEX + 1] : null;

if (!PROJECT_ID || !TOKEN) {
  console.error('Missing required env vars: NEXT_PUBLIC_SANITY_PROJECT_ID and SANITY_API_READ_TOKEN');
  process.exit(1);
}

const lines = [];
function log(msg = '') { lines.push(msg); console.log(msg); }

async function checkSingletons() {
  log('## Singletons\n');
  log('| Schema | Status | Last Edited |');
  log('|--------|--------|-------------|');

  const singletons = ['profile', 'aboutSection', 'siteSettings', 'techStack', 'resume'];
  for (const type of singletons) {
    const doc = await sanityQuery(`*[_type == "${type}"][0]{_id, _updatedAt}`, TOKEN, PROJECT_ID, DATASET);
    if (doc) {
      const age = Math.round((Date.now() - new Date(doc._updatedAt).getTime()) / 86400000);
      log(`| ${type} | ✅ | ${age}d ago |`);
    } else {
      log(`| ${type} | ❌ MISSING | — |`);
    }
  }
  log('');
}

async function checkCollections() {
  log('## Collections\n');
  log('| Schema | Count | With Images | With Alt Text |');
  log('|--------|-------|-------------|---------------|');

  const collections = [
    { type: 'project', imageField: 'image', altField: 'image.alt' },
    { type: 'experience', imageField: 'images', altField: null },
    { type: 'certification', imageField: 'image', altField: 'image.alt' },
    { type: 'galleryImage', imageField: 'image', altField: 'alt' },
    { type: 'post', imageField: 'mainImage', altField: 'mainImage.alt' },
  ];

  for (const c of collections) {
    const count = await sanityQuery(`count(*[_type == "${c.type}"])`, TOKEN, PROJECT_ID, DATASET);
    const withImages = c.imageField
      ? await sanityQuery(`count(*[_type == "${c.type}" && defined(${c.imageField})])`, TOKEN, PROJECT_ID, DATASET)
      : count;
    const withAlt = c.altField
      ? await sanityQuery(`count(*[_type == "${c.type}" && defined(${c.altField})])`, TOKEN, PROJECT_ID, DATASET)
      : count;
    log(`| ${type} | ${count} | ${withImages}/${count} | ${withAlt}/${count} |`);
  }
  log('');
}

async function checkDuplicates() {
  log('## Duplicate Check\n');

  const projects = await sanityQuery(
    `*[_type == "project"]{ _id, title, slug }`,
    TOKEN, PROJECT_ID, DATASET
  );

  if (!projects || projects.length === 0) {
    log('No projects to check.\n');
    return;
  }

  const slugMap = {};
  for (const p of projects) {
    const slug = (p.slug?.current || '').trim().toLowerCase();
    if (!slug) continue;
    if (!slugMap[slug]) slugMap[slug] = [];
    slugMap[slug].push(p);
  }

  const dupes = Object.entries(slugMap).filter(([, docs]) => docs.length > 1);
  if (dupes.length === 0) {
    log('✅ No duplicate slugs found\n');
  } else {
    log(`⚠️ Found ${dupes.length} duplicate slug group(s):\n`);
    for (const [slug, docs] of dupes) {
      log(`- **"${slug}"**: ${docs.map(d => `\`${d._id}\``).join(', ')}`);
    }
    log('');
  }
}

async function checkReferences() {
  log('## Reference Integrity\n');

  const brokenCerts = await sanityQuery(
    `count(*[_type == "certification" && !defined(issuer)])`,
    TOKEN, PROJECT_ID, DATASET
  );
  const brokenPosts = await sanityQuery(
    `count(*[_type == "post" && !defined(author)])`,
    TOKEN, PROJECT_ID, DATASET
  );
  const orphanGallery = await sanityQuery(
    `count(*[_type == "galleryImage" && !defined(category)])`,
    TOKEN, PROJECT_ID, DATASET
  );

  if (brokenCerts === 0 && brokenPosts === 0 && orphanGallery === 0) {
    log('✅ All references valid\n');
  } else {
    if (brokenCerts > 0) log(`- ❌ ${brokenCerts} certifications missing issuer`);
    if (brokenPosts > 0) log(`- ❌ ${brokenPosts} posts missing author`);
    if (orphanGallery > 0) log(`- ⚠️ ${orphanGallery} gallery images without category`);
    log('');
  }
}

async function main() {
  log('# Sanity Data Health Report');
  log(`Generated: ${new Date().toISOString()}\n`);

  await checkSingletons();
  await checkCollections();
  await checkDuplicates();
  await checkReferences();

  log('---');
  log('*Report generated by sanity-migrate/health-report.mjs*');

  if (OUTPUT_PATH) {
    mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
    const tmpPath = `${OUTPUT_PATH}.${randomUUID()}.tmp`;
    writeFileSync(tmpPath, lines.join('\n'), 'utf-8');
    renameSync(tmpPath, OUTPUT_PATH);
    console.log(`\nReport saved to ${OUTPUT_PATH}`);
  }
}

main().catch(console.error);
