import type {
  BlogPost,
  Certification,
  Experience,
  GalleryItem,
  Membership,
  Profile,
  Project,
  Recommendation,
  SocialLink,
  Technology,
} from '@/types';
import { SITE_URL } from '@/lib/site-config';

export interface CmsContent {
  seoSettings: {
    siteTitle: string;
    siteDescription: string;
    canonicalUrl: string;
    ogImageUrl: string;
    twitterImageUrl: string;
    noindex: boolean;
    nofollow: boolean;
  };
  profile: Profile;
  siteSettings: {
    footer: {
      leadText: string;
      linkLabel: string;
      copyright: string;
      backToPortfolioLabel: string;
      contactPrompt: string;
    };
    blog: {
      title: string;
      description: string;
      backLabel: string;
    };
  };
  hero: {
    roles: string[];
    availabilityLabel: string;
    profileImageUrl: string;
  };
  about: {
    paragraphs: string[];
  };
  experiences: Experience[];
  projects: Project[];
  certifications: Certification[];
  galleryImages: GalleryItem[];
  memberships: Membership[];
  recommendations: Recommendation[];
  socialLinks: SocialLink[];
  technologies: Technology[];
  techCategories: Record<string, Technology[]>;
  blogPosts: BlogPost[];
}

export const fallbackBlogPosts: BlogPost[] = [
  {
    id: 'from-for-loops-to-fullstack',
    slug: 'from-for-loops-to-full-stack-engineer',
    title: 'From For Loops to Full-Stack Engineer',
    excerpt: 'How I went from writing basic Java for loops in 2022 to building full-stack applications with modern frameworks, AI integration, and production deployments.',
    content: '# From For Loops to Full-Stack Engineer\n\nI remember the day I finally understood for loops. It was in my first Java programming class, and the concept of iteration — repeating an action until a condition is met — felt like magic. Little did I know that the same principle applied to my own growth as a developer.\n\n## The Java Years\n\nMy formal programming education started with Java. Not JavaScript, not Python — good old-fashioned Java with its explicit types, verbose syntax, and object-oriented everything.\n\nI wrote programs that would make any professional developer cringe:\n\n```java\npublic class Main {\n    public static void main(String[] args) {\n        for (int i = 0; i < 10; i++) {\n            System.out.println("Count: " + i);\n        }\n    }\n}\n```\n\nBut those for loops taught me fundamentals that still matter today: **control flow**, **iteration**, **conditions**, and **the logic of breaking problems into steps**.\n\nI built small projects — a grade checker, a simple banking system, a food ordering app. They were basic, but each one stretched what I thought I could do.\n\n## The 2023 Wake-Up Call\n\nThen came 2023. Everything changed.\n\nAI went mainstream. ChatGPT showed up, then GitHub Copilot, then a dozen other tools. Suddenly, the landscape wasn\'t just about knowing Java or C# — it was about how fast you could build, how creatively you could use new tools, and how well you could orchestrate multiple technologies together.\n\nI realized that if I wanted to grow, I needed to:\n\n1. **Go beyond one language** — Java was great, but the world runs on JavaScript, TypeScript, Python, and more\n2. **Learn the modern stack** — APIs, databases, cloud deployment, version control\n3. **Embrace AI as a tool** — not a crutch, but a force multiplier\n4. **Build real things** — not just academic exercises, but applications people actually use\n\n## The Full-Stack Leap\n\nI started with web development. HTML and CSS felt like a creative playground after years of console applications. Then JavaScript clicked — and suddenly, I could build things that ran in a browser, that people could interact with, that looked and felt like real software.\n\nNext came the backend. Node.js made JavaScript server-side possible. I learned REST APIs, database design, and authentication. I moved from PostgreSQL to MongoDB and back again, understanding when to use each.\n\nReact and Next.js followed. The component model made sense immediately — it was like building with Lego blocks, each piece reusable and composable.\n\n```typescript\n// From Java classes to React components\nfunction HelloWorld({ name }: { name: string }) {\n  return <h1>Hello, {name}!</h1>;\n}\n// Same idea, different decade\n```\n\n## Projects That Built Me\n\nEvery project taught me something:\n\n| Year | Project | What I Learned |\n|------|---------|---------------|\n| 2022 | First Java programs | Variables, loops, conditions |\n| 2023 | Billing Management System | JavaFX, MySQL, desktop UI |\n| 2024 | CaseMaster | Office integration, email systems, architecture |\n| 2024 | Student Attendance System | Barcode hardware, camera APIs, offline sync |\n| 2024 | Biometric IoT Attendance | Hardware integration, fingerprint sensors |\n| 2025 | Namias Portfolio | Next.js, TypeScript, testing, CI/CD |\n\n## The Transformation\n\nLooking back, the transition from for loops to full-stack wasn\'t a single leap — it was hundreds of small steps:\n\n- **25+ GitHub repositories** — each one a snapshot of what I was learning\n- **Multiple tech stacks** — Java, C#, Python, TypeScript, JavaScript\n- **From desktop to web to mobile to IoT** — following curiosity wherever it led\n- **From consumer to creator** — not just using tools, but building them\n\n## What I\'d Tell My Earlier Self\n\nIf I could go back and talk to the version of me staring at that first for loop:\n\n1. **Your fundamentals are solid** — loops, conditions, data structures — they matter in every language\n2. **Don\'t stay in one lane** — try frontend, try backend, try hardware. Everything connects.\n3. **Build in public** — put your code on GitHub. Share what you learn. The connections you make are invaluable.\n4. **AI is your partner, not your replacement** — learn to use it to accelerate, not replace, your thinking\n\n## Where I Am Now\n\nToday, I build production applications with modern frameworks. I integrate AI into real products. I automate workflows that save hours of manual work. I deploy to the cloud with CI/CD pipelines and automated testing.\n\nBut I still start every new project the same way: with a simple for loop, testing that the basics work before moving on.',
    date: '2025-11-05',
    readTime: '5 min read',
    tags: ['growth', 'fullstack', 'journey', 'transformation'],
    coverImage: '',
    featured: false,
    metaTitle: 'From For Loops to Full-Stack Engineer',
    metaDescription: 'How I went from writing basic Java for loops in 2022 to building full-stack applications with modern frameworks, AI integration, and production deployments.',
  },
  {
    id: 'student-attendance-system',
    slug: 'building-student-attendance-management-system-from-scratch',
    title: 'Building Student Attendance Management System from Scratch',
    excerpt: 'Building a full-featured attendance tracking system with barcode scanning, mobile app, and admin dashboard using C# and PostgreSQL.',
    content: '# Building Student Attendance Management System from Scratch\n\n[youtube:zWqLW4S-Y-A "Project Demo — Student Attendance Management System"]\n\nEvery school has the same problem: manual attendance tracking. Paper sheets get lost, Excel files become messy, and teachers spend more time on admin work than actual teaching.\n\nI built the **Student Attendance Management System** to solve that. It\'s a barcode-based attendance tracking system with a desktop application for admins and a mobile app for teachers to scan barcodes on the go.\n\n## The Problem\n\nAt the University of Caloocan City, attendance was tracked the old-fashioned way — calling names, passing around sheets, and manually entering data into spreadsheets. It was:\n- **Time-consuming** — 15+ minutes per class just for attendance\n- **Error-prone** — manual entry meant typos, missed names, and lost records\n- **Hard to analyze** — no easy way to see patterns or generate reports\n\nThe goal was simple: build a system where a teacher could mark attendance for an entire class in under 30 seconds.\n\n## Tech Stack\n\n| Component | Technology |\n|-----------|-----------|\n| Desktop App | C# (.NET Framework) |\n| Mobile Scanner | C# with camera integration |\n| Database | PostgreSQL |\n| UI Framework | MaterialDesign UI |\n| Architecture | MVVM Pattern |\n| Barcode Format | Standard 1D barcodes |\n\n## How It Works\n\n**For teachers:** Open the mobile app, point the camera at a student\'s barcode ID card, and attendance is logged instantly. No typing, no searching — just scan and go.\n\n**For admins:** The desktop dashboard provides real-time attendance data, reports, and analytics. You can filter by date, class, student, or attendance status.\n\n```csharp\n// Core attendance scanning logic\nprivate void OnBarcodeScanned(string studentId)\n{\n    var attendance = new Attendance\n    {\n        StudentId = studentId,\n        Date = DateTime.Now.Date,\n        Time = DateTime.Now.TimeOfDay,\n        Status = true // Present\n    };\n\n    _attendanceRepository.LogAttendance(attendance);\n    UpdateDashboard();\n}\n```\n\n## Key Features\n\n### Barcode Scanning\nEach student gets a unique barcode on their ID card. Teachers scan using any device with a camera. The system works offline and syncs when connectivity is available.\n\n### Admin Dashboard\nA comprehensive dashboard showing:\n- Attendance statistics and trends\n- Real-time monitoring\n- Customizable reports\n- Absenteeism analysis\n\n### Role-Based Access\n- **Teachers:** Mark attendance, view their classes\n- **Admins:** Full access — user management, reports, system settings\n- **Multi-factor authentication** for security\n\n[youtube:zWqLW4S-Y-A "Full Demo Walkthrough"]\n\n## Database Design\n\nThe system uses PostgreSQL with a normalized schema:\n\n```sql\nCREATE TABLE Students (\n    Id SERIAL PRIMARY KEY,\n    Name VARCHAR(100),\n    Course VARCHAR(50),\n    Year VARCHAR(10),\n    Section VARCHAR(10),\n    StudentId TEXT UNIQUE,\n    Archived BOOLEAN DEFAULT FALSE\n);\n\nCREATE TABLE Attendance (\n    Id SERIAL PRIMARY KEY,\n    StudentId INTEGER REFERENCES Students(StudentId),\n    Status BOOLEAN,\n    Date DATE,\n    Time TIME,\n    Archived BOOLEAN DEFAULT FALSE\n);\n```\n\n## Challenges I Faced\n\n### Barcode Camera Integration\nGetting the camera to scan barcodes reliably was the hardest part. Different lighting conditions, angles, and barcode qualities meant I had to fine-tune the scanning parameters extensively.\n\n**Lesson learned:** Always test with real hardware early. Simulators don\'t tell you how the camera will behave in a dimly lit classroom.\n\n### Offline-First Design\nSchools don\'t always have reliable internet. I built the mobile app to queue scans locally and sync when connectivity returns. This required careful conflict resolution to avoid duplicate entries.\n\n### MVVM Architecture\nThis was my first real project using the MVVM pattern. It took a while to wrap my head around data binding and separation of concerns, but once it clicked, the code became much cleaner and more maintainable.\n\n## Results\n\n- **14 GitHub stars** — real engagement from other developers\n- **5 forks** — people actually found it useful enough to build on\n- **Live demo** deployed on GitHub Pages\n- **Barcode-based** — 30-second attendance for a class of 40\n\n## What I Learned\n\nThis project taught me more than any course ever could:\n\n1. **Full-stack desktop development** — C#, PostgreSQL, UI design\n2. **Camera integration** — working with hardware APIs\n3. **Offline architecture** — designing for unreliable networks\n4. **MVVM pattern** — clean separation of concerns\n5. **User research** — talking to actual teachers about their pain points\n\n## Try It Yourself\n\nThe project is open source on GitHub:\n\n- **GitHub:** [Student-Attendance-Management-System](https://github.com/PP-Namias/Student-Attendance-Management-System)\n- **Live Demo:** [pp-namias.github.io/Student-Attendance-Management-System](https://pp-namias.github.io/Student-Attendance-Management-System)\n- **License:** MIT',
    date: '2025-09-10',
    readTime: '6 min read',
    tags: ['csharp', 'postgresql', 'desktop', 'attendance', 'barcode', 'project'],
    coverImage: '',
    featured: false,
    metaTitle: 'Building Student Attendance Management System from Scratch',
    metaDescription: 'Building a full-featured attendance tracking system with barcode scanning, mobile app, and admin dashboard using C# and PostgreSQL.',
  },
  {
    id: 'hello-world-first-code',
    slug: 'hello-world-the-day-i-wrote-my-first-line-of-code',
    title: 'Hello World: The Day I Wrote My First Line of Code',
    excerpt: 'What started as pure curiosity in 2022 turned into a lifelong passion for building software. That first Hello World opened the door to an entirely new world of problem-solving, creativity, and endless possibilities.',
    content: '# Hello World: The Day I Wrote My First Line of Code\n\nI still remember the exact moment. It was late 2022, and I was staring at my screen, watching a blinking cursor on a black terminal window. I typed `cout << "Hello World";`, hit Enter, and saw those two words appear back at me. That was it. That was the moment everything changed.\n\nI had zero idea what I was doing. I didn\'t know what a compiler was, what syntax meant, or why I needed semicolons at the end of every line. All I knew was that I told the computer to do something, and it did it. That feeling — of being in control, of creating something from nothing — was addictive.\n\n## How It All Started\n\nI wasn\'t the kid who grew up taking apart computers or building websites in middle school. I discovered programming almost by accident. A friend showed me a freeCodeCamp tutorial, and I was hooked after writing my first HTML tag.\n\nThe first few weeks were a blur of:\n\n- **Online tutorials** — freeCodeCamp, YouTube, and any resource I could find\n- **Endless Google searches** — every error message was a new mystery to solve\n- **Late-night debugging sessions** — spending hours finding a missing semicolon or a mismatched bracket\n- **Tiny victories** — getting a button to change color, making text appear on click\n\nI didn\'t have a structured curriculum or a mentor. I had curiosity and stubbornness. And honestly? That was enough.\n\n## Learning the Fundamentals\n\nI started with the basics: HTML and CSS. I remember building my first webpage — an ugly, mismatched mess of divs and inline styles. But it was *mine*. I made it. And when I opened it in a browser and saw it render, I felt like I had built a skyscraper.\n\n```html\n<!DOCTYPE html>\n<html>\n<head>\n  <title>My First Website</title>\n</head>\n<body>\n  <h1>Hello World!</h1>\n  <p>This is my first website.</p>\n</body>\n</html>\n```\n\nThen came JavaScript. Variables, functions, conditionals — concepts that seemed abstract at first slowly clicked into place. I\'ll never forget understanding my first `if` statement. It felt like I had unlocked a superpower. The computer was making decisions based on my logic.\n\nI built tiny projects to practice:\n\n- A **calculator** that could add, subtract, multiply, and divide\n- A **to-do list** app that stored tasks (in memory — localStorage was a later discovery)\n- A **personal blog** using just HTML, CSS, and a touch of JavaScript\n\nEach project taught me something new. The calculator taught me about event listeners. The to-do list taught me about arrays and DOM manipulation. The blog taught me about page structure and navigation.\n\n## Why I Kept Going\n\nProgramming is hard. Especially when you\'re learning alone. There were plenty of moments when I wanted to quit — when a bug made no sense, when nothing worked, when I felt like I just wasn\'t smart enough.\n\nBut I kept coming back. Not because I had to, but because I genuinely loved it. There\'s something magical about the process: you have an idea, you write code, and something real appears on the screen. It\'s creation in its purest form.\n\nI spent hours debugging and loving every minute of it. Every error I solved made me better. Every project I finished gave me confidence to tackle something harder.\n\n## What That First Hello World Taught Me\n\nLooking back, that first `cout << "Hello World";` taught me more than just syntax. It taught me:\n\n1. **Programming is for everyone** — you don\'t need a degree to start. You just need curiosity and persistence.\n2. **The only way to learn is to build** — tutorials are great, but real learning happens when you\'re stuck on your own project.\n3. **Debugging is not failure** — it\'s the process of understanding. Every bug is a lesson.\n4. **Small wins compound** — a Hello World becomes a calculator, becomes a blog, becomes a full application.\n\nI didn\'t know it then, but that first line of code was the start of a journey that would take me from Hello World to building AI chatbots, enterprise automation systems, and production applications serving thousands of users.\n\n## Looking Forward\n\nIf you\'re reading this and you\'re just starting your coding journey: keep going. That blinking cursor on your screen is an invitation. Type something. Break something. Fix something. Learn something.\n\nThe first step is always the hardest. But once you see those two words — Hello World — you\'ll understand why we never stop.',
    date: '2025-03-15',
    readTime: '4 min read',
    tags: ['beginner', 'self-taught', 'web-development', 'html', 'css', 'javascript'],
    coverImage: '',
    featured: false,
    metaTitle: 'Hello World: The Day I Wrote My First Line of Code',
    metaDescription: 'What started as pure curiosity in 2022 turned into a lifelong passion for building software. That first Hello World opened the door to an entirely new world.',
  },
  {
    id: 'welcome-intro',
    slug: 'hi-welcome-to-my-blog-portfolio',
    title: 'Hi - Welcome to my blog-portfolio!',
    excerpt: 'A short introduction to who I am, how I got into programming, what I build today, and where the road ahead is taking me.',
    content: '# Hi - Welcome to my blog-portfolio!\n\nHi! I\'m Jhon Keneth Ryan B. Namias, a passionate full-stack engineer and AI automation specialist.',
    date: '2026-05-20',
    readTime: '4 min read',
    tags: ['intro', 'career', 'ai', 'fullstack', 'personal'],
    coverImage: '',
    featured: true,
    metaTitle: 'Hi - Welcome to my blog-portfolio!',
    metaDescription: 'A short introduction to Jhon Keneth Ryan B. Namias — full-stack engineer, AI automation specialist.',
  },
  {
    id: 'gitgoing-webinar',
    slug: 'gitgoing-computer-science-github-webinar',
    title: 'GitGoing - Computer Science GitHub Webinar!',
    excerpt: 'My experience as a Special Guest Speaker at the University of Caloocan City\'s GitGoing webinar.',
    content: '# GitGoing - Computer Science GitHub Webinar!\n\nI really do believe that collaboration among developers is one of the keys to the success of any program.',
    date: '2026-02-28',
    readTime: '6 min read',
    tags: ['git', 'github', 'webinar', 'speaking', 'collaboration', 'ucc'],
    coverImage: '',
    featured: true,
    metaTitle: 'GitGoing - Computer Science GitHub Webinar!',
    metaDescription: 'My experience as a Special Guest Speaker at the University of Caloocan City\'s GitGoing webinar.',
  },
  {
    id: 'namias-experience-2026',
    slug: 'my-experience-as-a-developer-in-2026',
    title: 'My Experience as a Developer in 2026',
    excerpt: 'A reflection on my journey as a developer starting in 2020, the 2023 AI shift, and the lesson of BALANCE.',
    content: '# My Experience as a Developer in 2026\n\nHi! I\'m Jhon Keneth Ryan B. Namias, currently pursuing Computer Science.',
    date: '2026-06-05',
    readTime: '8 min read',
    tags: ['experience', 'reflection', 'ai', 'cs50', 'balance', 'learning', 'developer-journey'],
    coverImage: '',
    featured: false,
    metaTitle: 'My Experience as a Developer in 2026',
    metaDescription: 'Jhon Keneth Ryan B. Namias reflects on coding since 2020, CS50, the 2023 AI shift, and why BALANCE matters.',
  },
];

export function buildTechCategories(technologies: Technology[]): Record<string, Technology[]> {
  return technologies.reduce<Record<string, Technology[]>>((acc, technology) => {
    if (!acc[technology.category]) {
      acc[technology.category] = [];
    }

    acc[technology.category].push(technology);
    return acc;
  }, {});
}

const emptyProfile: Profile = {
  name: '',
  title: '',
  email: '',
  phone: '',
  location: '',
  github: '',
  linkedin: '',
  summary: '',
  highlights: {
    yearsExperience: 0,
    projectsCompleted: 0,
    primaryTechnologies: [],
  },
  education: [],
};

export const fallbackCmsContent: CmsContent = {
  seoSettings: {
    siteTitle: 'Jhon Keneth Namias | Portfolio',
    siteDescription: 'Personal portfolio of Jhon Keneth Namias.',
    canonicalUrl: SITE_URL,
    ogImageUrl: '/og-image.svg',
    twitterImageUrl: '/og-image.svg',
    noindex: false,
    nofollow: false,
  },
  profile: emptyProfile,
  siteSettings: {
    footer: {
      leadText: '',
      linkLabel: '',
      copyright: '',
      backToPortfolioLabel: 'Back to Portfolio',
      contactPrompt: 'Send a message',
    },
    blog: {
      title: 'Blog',
      description: 'Thoughts on AI, software engineering, cloud development, and more.',
      backLabel: 'Back to Portfolio',
    },
  },
  hero: {
    roles: [],
    availabilityLabel: '',
    profileImageUrl: '',
  },
  about: {
    paragraphs: [
      "I'm a full-stack software engineer specializing in React, TypeScript, Node.js, and Python. I build production systems across enterprise, AI automation, healthcare, and IoT \u2014 from designing backend architecture to shipping polished user interfaces.",
      "I've delivered 5+ live applications serving over 1,000 concurrent users, including an enterprise HRIS for 500+ employees and 8 deployed AI chatbot systems. My work spans the full lifecycle \u2014 system design, database architecture, API development, and frontend engineering \u2014 always with a focus on reliability and measurable outcomes.",
      "I graduated Cum Laude with a BS in Computer Science from the University of Caloocan City (Batch 2026), recognized as a Dean's Lister throughout my studies. I'm currently targeting fullstack, AI/automation, or backend engineering roles where technical ownership and cross-functional execution drive real product impact.",
    ],
  },
  experiences: [],
  projects: [
    {
      title: 'Namias Portfolio',
      image: '',
      description: 'Production portfolio with AI chat, Sanity CMS, and 278 tests',
      tags: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Sanity', 'Web Application'],
      year: 2025,
      category: 'Web Application',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Portfolio',
      liveURL: 'https://namias.tech',
      processURL: null,
      detailURL: null,
      status: 'in-progress',
      tier: 'featured',
      showcaseDetail: false,
      shortDescription: 'Production portfolio with AI chat, Sanity CMS, and 278 tests',
      highlights: ['278 tests with react-doctor 100/100 score', '19 CI/CD workflows with GitHub Actions', 'AI chat integration', 'PentestAgent security scanning'],
      githubRepo: 'Portfolio',
      slug: 'namias-portfolio',
    },
    {
      title: 'CaseMaster',
      image: '',
      description: 'A comprehensive case management system with Office login and email integration',
      tags: ['Desktop Application', 'Microsoft Office', 'Email Integration', 'Case Management'],
      year: 2024,
      category: 'Desktop Application',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/CaseMaster',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'A comprehensive case management system with Office login and email integration',
      highlights: ['Microsoft Office integration', 'Email management system', 'Notion-style case tracker', 'Audit logs and archive system'],
      githubRepo: 'CaseMaster',
      slug: 'casemaster',
    },
    {
      title: 'Gigachad Accounting System',
      image: '',
      description: 'Full-featured accounting system with financial tracking and reporting',
      tags: ['Desktop Application', 'Financial Tracking', 'Reporting', 'Multi-user'],
      year: 2024,
      category: 'Desktop Application',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Gigachad-Accounting-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Full-featured accounting system with financial tracking and reporting',
      highlights: ['Financial transaction tracking', 'Invoice management', 'Reporting dashboard', 'Multi-user support'],
      githubRepo: 'Gigachad-Accounting-System',
      slug: 'gigachad-accounting-system',
    },
    {
      title: 'Student Attendance System',
      image: '',
      description: 'Barcode-based attendance tracking with mobile app and admin dashboard',
      tags: ['Education Tech', 'Barcode', 'Mobile App', 'Admin Dashboard'],
      year: 2024,
      category: 'Education Tech',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Student-Attendance-Management-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Barcode-based attendance tracking with mobile app and admin dashboard',
      highlights: ['Barcode-based attendance tracking', 'Mobile app for teachers', 'Admin dashboard with analytics', 'Role-based access control'],
      githubRepo: 'Student-Attendance-Management-System',
      slug: 'student-attendance-system',
    },
    {
      title: 'Billing Management System',
      image: '',
      description: 'Shop management with product CRUD, billing logs, and Excel export',
      tags: ['Desktop Application', 'JavaFX', 'MySQL', 'Excel Export'],
      year: 2024,
      category: 'Desktop Application',
      role: 'Backend Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Billing-Management-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Shop management with product CRUD, billing logs, and Excel export',
      highlights: ['JavaFX 21 modern UI', 'MySQL database integration', 'Excel export functionality', 'Multi-contributor collaboration'],
      githubRepo: 'Billing-Management-System',
      slug: 'billing-management-system',
    },
    {
      title: 'Biometric IoT Attendance',
      image: '',
      description: 'Biometric attendance using IoT fingerprint scanner hardware integration',
      tags: ['IoT', 'Fingerprint Scanner', 'Embedded Systems', 'Hardware Integration'],
      year: 2024,
      category: 'IoT',
      role: 'IoT Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Biometric-Attendance-System-Using-IOT',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Biometric attendance using IoT fingerprint scanner hardware integration',
      highlights: ['Fingerprint scanner integration', 'IoT hardware communication', 'Real-time attendance logging', 'Embedded systems programming'],
      githubRepo: 'Biometric-Attendance-System-Using-IOT',
      slug: 'biometric-iot-attendance',
    },
    {
      title: 'Whisper AI Real-Time',
      image: '',
      description: 'Real-time speech-to-text powered by OpenAI Whisper with GPU acceleration',
      tags: ['AI/ML', 'OpenAI Whisper', 'Speech-to-Text', 'GPU Acceleration'],
      year: 2024,
      category: 'AI/ML',
      role: 'AI/ML Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Whisper_AI_Real_Time',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Real-time speech-to-text powered by OpenAI Whisper with GPU acceleration',
      highlights: ['Real-time speech-to-text transcription', 'Multiple model sizes for different needs', 'GPU acceleration support', 'State-of-the-art AI accuracy'],
      githubRepo: 'Whisper_AI_Real_Time',
      slug: 'whisper-ai-real-time',
    },
    {
      title: 'Whisper AI Subtitles',
      image: '',
      description: 'Generate subtitles and transcriptions from audio/video with Whisper AI',
      tags: ['AI/ML', 'OpenAI Whisper', 'Subtitle Generation', 'Audio Processing'],
      year: 2024,
      category: 'AI/ML',
      role: 'AI/ML Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Whisper-AI-Generate-Subtitles-Transcriptions',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Generate subtitles and transcriptions from audio/video with Whisper AI',
      highlights: ['Audio/video subtitle generation', 'Multiple output formats', 'Batch processing support', 'High accuracy transcription'],
      githubRepo: 'Whisper-AI-Generate-Subtitles-Transcriptions',
      slug: 'whisper-ai-subtitles',
    },
    {
      title: 'Aura AI Discord Bot',
      image: '',
      description: 'AI-powered Discord bot with smart moderation and community features',
      tags: ['Bot', 'Discord.js', 'AI Moderation', 'Community Tools'],
      year: 2025,
      category: 'Bot',
      role: 'Bot Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Aura-AI-Discord-Bot',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: false,
      shortDescription: 'AI-powered Discord bot with smart moderation and community features',
      highlights: ['AI-powered moderation', 'Community engagement features', 'Discord.js integration', 'Automated responses'],
      githubRepo: 'Aura-AI-Discord-Bot',
      slug: 'aura-ai-discord-bot',
    },
    {
      title: 'Pre-Enrollment System',
      image: '',
      description: 'Student pre-enrollment management for Young Achievers School of Caloocan',
      tags: ['Education Tech', 'Student Management', 'Web Application', 'Database'],
      year: 2024,
      category: 'Education Tech',
      role: 'Full-Stack Developer',
      featured: true,
      repositoryURL: 'https://github.com/PP-Namias/Pre-enrollment-Management-System',
      liveURL: 'https://pp-namias.github.io/Pre-enrollment-Management-System',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'featured',
      showcaseDetail: true,
      shortDescription: 'Student pre-enrollment management for Young Achievers School of Caloocan',
      highlights: ['Student data management', 'Enrollment workflow automation', 'Database design and optimization', 'Web application for school admin'],
      githubRepo: 'Pre-enrollment-Management-System',
      slug: 'pre-enrollment-system',
    },
    {
      title: 'Java Rice',
      image: '',
      description: 'An interactive food ordering system built with Java',
      tags: ['Desktop Application', 'Java', 'Food Ordering', 'Java Swing'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Java-Rice',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: true,
      shortDescription: 'An interactive food ordering system built with Java',
      highlights: ['Interactive food ordering UI', 'Order management system', 'Java Swing interface', 'Database integration'],
      githubRepo: 'Java-Rice',
      slug: 'java-rice',
    },
    {
      title: 'ATM System',
      image: '',
      description: 'Automated teller machine application with command line interface',
      tags: ['Desktop Application', 'Python', 'CLI', 'Banking'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/ATM-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Automated teller machine application with command line interface',
      highlights: ['CLI-based interface', 'Transaction processing', 'Account management', 'Python implementation'],
      githubRepo: 'ATM-System',
      slug: 'atm-system',
    },
    {
      title: 'Car Dealership Manager',
      image: '',
      description: 'Car dealership management system built entirely in C++',
      tags: ['Desktop Application', 'C++', 'File I/O', 'Vehicle Management'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Car-Dealership-Management-Program',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Car dealership management system built entirely in C++',
      highlights: ['Vehicle inventory management', 'Sales tracking', 'C++ implementation', 'File I/O operations'],
      githubRepo: 'Car-Dealership-Management-Program',
      slug: 'car-dealership-manager',
    },
    {
      title: 'UCC Student Portal',
      image: '',
      description: 'Front-end design for University of Caloocan City student web application',
      tags: ['Web Application', 'HTML', 'CSS', 'Responsive Design'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/UCC-Student-Portal',
      liveURL: 'https://pp-namias.github.io/UCC-Student-Portal',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Front-end design for University of Caloocan City student web application',
      highlights: ['Responsive student portal UI', 'Modern HTML/CSS design', 'User-friendly navigation', 'University branding'],
      githubRepo: 'UCC-Student-Portal',
      slug: 'ucc-student-portal',
    },
    {
      title: 'UCC Access Module',
      image: '',
      description: 'Module access system for the University of Caloocan City',
      tags: ['Web Application', 'PHP', 'Authentication', 'Database'],
      year: 2023,
      category: 'Web Application',
      role: 'Full-Stack Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/UCC-Access-Module',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Module access system for the University of Caloocan City',
      highlights: ['Secure module access', 'User authentication', 'PHP backend', 'Database integration'],
      githubRepo: 'UCC-Access-Module',
      slug: 'ucc-access-module',
    },
    {
      title: 'Point of Sale System',
      image: '',
      description: 'Point of sale system for retail transaction management',
      tags: ['Desktop Application', 'Transaction Processing', 'Inventory', 'Retail'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Point-of-Sale-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Point of sale system for retail transaction management',
      highlights: ['Transaction processing', 'Product catalog', 'Receipt generation', 'Inventory tracking'],
      githubRepo: 'Point-of-Sale-System',
      slug: 'point-of-sale-system',
    },
    {
      title: 'Banking System',
      image: '',
      description: 'Banking system with account management and transaction processing',
      tags: ['Desktop Application', 'Java', 'Banking', 'Transaction Processing'],
      year: 2023,
      category: 'Desktop Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Banking-System',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Banking system with account management and transaction processing',
      highlights: ['Account management', 'Transaction processing', 'Balance inquiries', 'Java implementation'],
      githubRepo: 'Banking-System',
      slug: 'banking-system',
    },
    {
      title: 'DSA in Action',
      image: '',
      description: 'Data structures and algorithms implementation showcase',
      tags: ['Academic', 'Java', 'Data Structures', 'Algorithms'],
      year: 2023,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Final-Program-DSA',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Data structures and algorithms implementation showcase',
      highlights: ['Common data structures', 'Algorithm implementations', 'Performance analysis', 'Java programming'],
      githubRepo: 'Final-Program-DSA',
      slug: 'dsa-in-action',
    },
    {
      title: 'HCI Final Project',
      image: '',
      description: 'Human-Computer Interaction course final project with UI/UX focus',
      tags: ['Web Application', 'UI/UX', 'User Research', 'Prototyping'],
      year: 2023,
      category: 'Web Application',
      role: 'UI/UX Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/HCI-Final-Project',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Human-Computer Interaction course final project with UI/UX focus',
      highlights: ['User-centered design', 'Usability testing', 'Interface prototyping', 'HCI principles application'],
      githubRepo: 'HCI-Final-Project',
      slug: 'hci-final-project',
    },
    {
      title: 'GizDuino Program',
      image: '',
      description: 'GizDuino microcontroller programming for IoT and embedded systems',
      tags: ['IoT', 'Embedded Systems', 'C/C++', 'Microcontroller'],
      year: 2023,
      category: 'IoT',
      role: 'IoT Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/GizDuino-Program',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'GizDuino microcontroller programming for IoT and embedded systems',
      highlights: ['Microcontroller programming', 'Hardware interfacing', 'Sensor integration', 'C/C++ implementation'],
      githubRepo: 'GizDuino-Program',
      slug: 'gizduino-program',
    },
    {
      title: 'Philippines Tourism',
      image: '',
      description: 'Tourism case study website showcasing Philippine natural wonders',
      tags: ['Web Application', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Tourism-Case-Study',
      liveURL: 'https://pp-namias.github.io/Tourism-Case-Study',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Tourism case study website showcasing Philippine natural wonders',
      highlights: ['Responsive tourism website', 'Image gallery showcase', 'HTML/CSS/JS implementation', 'Cultural content presentation'],
      githubRepo: 'Tourism-Case-Study',
      slug: 'philippines-tourism',
    },
    {
      title: 'PHP Login System',
      image: '',
      description: 'PHP-based login and authentication system',
      tags: ['Web Application', 'PHP', 'Authentication', 'Session Management'],
      year: 2023,
      category: 'Web Application',
      role: 'Backend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/PHP-Login',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'PHP-based login and authentication system',
      highlights: ['User authentication', 'Session management', 'PHP backend', 'Database integration'],
      githubRepo: 'PHP-Login',
      slug: 'php-login-system',
    },
    {
      title: 'Simple Program Menu',
      image: '',
      description: 'Odd/Even check and looping exercise in Java',
      tags: ['Academic', 'Java', 'Control Flow', 'Looping'],
      year: 2023,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Simple-Program-Menu',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Odd/Even check and looping exercise in Java',
      highlights: ['Control flow implementation', 'Looping constructs', 'Java basics', 'Menu-driven program'],
      githubRepo: 'Simple-Program-Menu',
      slug: 'simple-program-menu',
    },
    {
      title: 'Passed or Failed',
      image: '',
      description: 'Grade checker application for student evaluation',
      tags: ['Academic', 'Java', 'Grade Calculation', 'Conditional Logic'],
      year: 2023,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Passed-or-Failed',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Grade checker application for student evaluation',
      highlights: ['Grade calculation logic', 'Conditional statements', 'Java implementation', 'Student evaluation tool'],
      githubRepo: 'Passed-or-Failed',
      slug: 'passed-or-failed',
    },
    {
      title: 'Full Name Rotation',
      image: '',
      description: 'Web system for rotating full name in various directions',
      tags: ['Web Application', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Full-Name-Rotation',
      liveURL: 'https://pp-namias.github.io/Full-Name-Rotation',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Web system for rotating full name in various directions',
      highlights: ['CSS text rotation effects', 'Interactive web interface', 'HTML/CSS/JS implementation', 'Midterm web systems project'],
      githubRepo: 'Full-Name-Rotation',
      slug: 'full-name-rotation',
    },
    {
      title: 'Galaxy Animation',
      image: '',
      description: 'Mesmerizing galaxy animation with pure HTML, CSS, and JavaScript',
      tags: ['Web Art', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Galaxy-Animation',
      liveURL: 'https://pp-namias.github.io/Galaxy-Animation',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Mesmerizing galaxy animation with pure HTML, CSS, and JavaScript',
      highlights: ['Pure CSS animations', 'No external dependencies', 'Particle system effects', 'Responsive canvas'],
      githubRepo: 'Galaxy-Animation',
      slug: 'galaxy-animation',
    },
    {
      title: 'CSS3 Robot Art',
      image: '',
      description: 'CSS robot web art created with pure HTML and CSS',
      tags: ['Web Art', 'HTML', 'CSS', 'Creative Design'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/CSS3-Robot-Web-Art',
      liveURL: 'https://pp-namias.github.io/CSS3-Robot-Web-Art',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'CSS robot web art created with pure HTML and CSS',
      highlights: ['Pure CSS artwork', 'Creative design', 'No JavaScript used', 'Web Systems activity'],
      githubRepo: 'CSS3-Robot-Web-Art',
      slug: 'css3-robot-art',
    },
    {
      title: 'CSS3 Robot Animation',
      image: '',
      description: 'Animated robot created with pure CSS3 animations',
      tags: ['Web Art', 'HTML', 'CSS3', 'Animation'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/CSS3-Robot-Animation',
      liveURL: 'https://pp-namias.github.io/CSS3-Robot-Animation',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Animated robot created with pure CSS3 animations',
      highlights: ['CSS3 keyframe animations', 'Character animation', 'Pure CSS implementation', 'Web Systems activity'],
      githubRepo: 'CSS3-Robot-Animation',
      slug: 'css3-robot-animation',
    },
    {
      title: 'CSS3 Egg Asteroid',
      image: '',
      description: 'Egg animation resembling an asteroid floating in space',
      tags: ['Web Art', 'HTML', 'CSS', 'Space Theme'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/CSS3-Egg-Asteroid',
      liveURL: 'https://pp-namias.github.io/CSS3-Egg-Asteroid',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Egg animation resembling an asteroid floating in space',
      highlights: ['Creative CSS animation', 'Space theme design', 'Pure HTML/CSS', 'Web Systems activity'],
      githubRepo: 'CSS3-Egg-Asteroid',
      slug: 'css3-egg-asteroid',
    },
    {
      title: 'Short Clip Animation',
      image: '',
      description: 'Interactive website showcasing the 2011 Bugatti Veyron sports car',
      tags: ['Web Art', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Short-Clip-Animation',
      liveURL: 'https://pp-namias.github.io/Short-Clip-Animation',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Interactive website showcasing the 2011 Bugatti Veyron sports car',
      highlights: ['Interactive car showcase', 'CSS animation effects', 'HTML/CSS/JS implementation', 'Web Systems activity'],
      githubRepo: 'Short-Clip-Animation',
      slug: 'short-clip-animation',
    },
    {
      title: 'Optimus Prime Animation',
      image: '',
      description: 'Transformer character animation created with CSS',
      tags: ['Web Art', 'HTML', 'CSS', 'Character Animation'],
      year: 2023,
      category: 'Web Art',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Optimus-Prime-Animation',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Transformer character animation created with CSS',
      highlights: ['Character CSS animation', 'Creative design', 'Pure CSS implementation', 'Web art project'],
      githubRepo: 'Optimus-Prime-Animation',
      slug: 'optimus-prime-animation',
    },
    {
      title: 'Floppy Bird',
      image: '',
      description: 'Flappy Bird clone game built with web technologies',
      tags: ['Game', 'HTML', 'Canvas', 'JavaScript'],
      year: 2023,
      category: 'Game',
      role: 'Game Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Floppy-Bird',
      liveURL: 'https://pp-namias.github.io/Floppy-Bird',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Flappy Bird clone game built with web technologies',
      highlights: ['Canvas-based game', 'Physics simulation', 'Score tracking', 'HTML/CSS/JS game'],
      githubRepo: 'Floppy-Bird',
      slug: 'floppy-bird',
    },
    {
      title: 'QR Code Generator',
      image: '',
      description: 'QR code generation application',
      tags: ['Utility', 'Java', 'Image Processing', 'QR Code'],
      year: 2023,
      category: 'Utility',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/QR-Code',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'QR code generation application',
      highlights: ['QR code generation', 'Java implementation', 'Image processing', 'Utility application'],
      githubRepo: 'QR-Code',
      slug: 'qr-code-generator',
    },
    {
      title: 'Calendar 2023',
      image: '',
      description: 'Interactive calendar website for Web Systems activity',
      tags: ['Web Application', 'HTML', 'CSS', 'JavaScript'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Calendar-2023',
      liveURL: 'https://pp-namias.github.io/Calendar-2023',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Interactive calendar website for Web Systems activity',
      highlights: ['Interactive calendar UI', 'Date navigation', 'HTML/CSS/JS', 'Web Systems activity'],
      githubRepo: 'Calendar-2023',
      slug: 'calendar-2023',
    },
    {
      title: 'GitHub Pages Bio',
      image: '',
      description: 'Personal bio data website hosted on GitHub Pages',
      tags: ['Web Application', 'HTML', 'CSS', 'GitHub Pages'],
      year: 2023,
      category: 'Web Application',
      role: 'Frontend Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/PP-Namias.github.io',
      liveURL: 'https://pp-namias.github.io',
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Personal bio data website hosted on GitHub Pages',
      highlights: ['GitHub Pages deployment', 'Personal branding', 'HTML/CSS/JS', 'Web Systems activity'],
      githubRepo: 'PP-Namias.github.io',
      slug: 'github-pages-bio',
    },
    {
      title: 'Grade 11 Website',
      image: '',
      description: 'Grade 11 ICT project for Computer Programming course',
      tags: ['Web Application', 'HTML', 'CSS', 'JavaScript'],
      year: 2022,
      category: 'Web Application',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Website-Project',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Grade 11 ICT project for Computer Programming course',
      highlights: ['Grade 11 coursework', 'HTML/CSS/JS', 'Computer Programming', 'ICT project'],
      githubRepo: 'Website-Project',
      slug: 'grade-11-website',
    },
    {
      title: 'CSD Freshman Bot',
      image: '',
      description: 'Discord bot with 20+ commands for the CSD Freshman server',
      tags: ['Bot', 'Discord.js', 'Node.js', 'Community Tools'],
      year: 2023,
      category: 'Bot',
      role: 'Bot Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/CSD-Bot',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Discord bot with 20+ commands for the CSD Freshman server',
      highlights: ['20+ commands', 'Server management features', 'Discord.js framework', 'Community tooling'],
      githubRepo: 'CSD-Bot',
      slug: 'csd-freshman-bot',
    },
    {
      title: 'UCC Programming Competition',
      image: '',
      description: 'Competition solutions for UCC Programming Competition 2023',
      tags: ['Academic', 'Java', 'Competitive Programming', 'Algorithms'],
      year: 2023,
      category: 'Academic',
      role: 'Competitive Programmer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/UCC-Programing-Competition-2023',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Competition solutions for UCC Programming Competition 2023',
      highlights: ['Algorithm problem solving', 'Competitive programming', 'Java implementation', 'Time-optimized solutions'],
      githubRepo: 'UCC-Programing-Competition-2023',
      slug: 'ucc-programming-competition',
    },
    {
      title: 'Java Program Hub',
      image: '',
      description: 'Collection of Java programs and testing exercises',
      tags: ['Academic', 'Java', 'Testing', 'Code Practice'],
      year: 2023,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Java-Program',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Collection of Java programs and testing exercises',
      highlights: ['Java program collection', 'Testing exercises', 'Learning repository', 'Code practice'],
      githubRepo: 'Java-Program',
      slug: 'java-program-hub',
    },
    {
      title: 'Cube Drift',
      image: '',
      description: 'Cube drift game built with web technologies',
      tags: ['Game', 'HTML', 'Canvas', 'JavaScript'],
      year: 2023,
      category: 'Game',
      role: 'Game Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Cube-Drift',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Cube drift game built with web technologies',
      highlights: ['Canvas-based game', 'Physics simulation', 'HTML/CSS/JS', 'Game development'],
      githubRepo: 'Cube-Drift',
      slug: 'cube-drift',
    },
    {
      title: 'Google Login',
      image: '',
      description: 'Google Authentication with Firebase using HTML, CSS, and JavaScript',
      tags: ['Web Application', 'Firebase', 'Google OAuth', 'Authentication'],
      year: 2023,
      category: 'Web Application',
      role: 'Full-Stack Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/Login-with-Google',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'standard',
      showcaseDetail: false,
      shortDescription: 'Google Authentication with Firebase using HTML, CSS, and JavaScript',
      highlights: ['Firebase authentication', 'Google OAuth integration', 'HTML/CSS/JS implementation', 'Secure login flow'],
      githubRepo: 'Login-with-Google',
      slug: 'google-login',
    },
    {
      title: 'Adventure Typer',
      image: '',
      description: 'Typing adventure game for learning touch typing',
      tags: ['Game', 'JavaScript', 'Educational', 'Typing Game'],
      year: 2023,
      category: 'Game',
      role: 'Game Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/AdventureTyper',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Typing adventure game for learning touch typing',
      highlights: ['Typing game mechanics', 'Adventure theme', 'JavaScript implementation', 'Educational game'],
      githubRepo: 'AdventureTyper',
      slug: 'adventure-typer',
    },
    {
      title: 'First Programming Project',
      image: '',
      description: 'Very first project in programming - the beginning of the coding journey',
      tags: ['Academic', 'C++', 'Learning', 'Fundamentals'],
      year: 2022,
      category: 'Academic',
      role: 'Developer',
      featured: false,
      repositoryURL: 'https://github.com/PP-Namias/My-first-project-in-programming',
      liveURL: null,
      processURL: null,
      detailURL: null,
      status: 'completed',
      tier: 'archived',
      showcaseDetail: false,
      shortDescription: 'Very first project in programming - the beginning of the coding journey',
      highlights: ['First programming project', 'Learning fundamentals', 'C++ implementation', 'Beginning of coding journey'],
      githubRepo: 'My-first-project-in-programming',
      slug: 'first-programming-project',
    },
  ],
  certifications: [],
  galleryImages: [],
  memberships: [],
  recommendations: [],
  socialLinks: [],
  technologies: [],
  techCategories: {},
  blogPosts: [],
};

fallbackCmsContent.blogPosts = fallbackBlogPosts;
